import { createHmac, timingSafeEqual } from 'node:crypto';
import { createReadStream } from 'node:fs';
import { mkdir, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, resolve, sep } from 'node:path';
import type { Readable } from 'node:stream';
import { apiPublicUrl, env } from '../../config/env.js';
import { CloudinaryStorageProvider, isCloudinaryKey } from './cloudinary.provider.js';

export interface SignedUrlOptions {
  /** Images only: resized preview of this width (providers that can't, return the original). */
  thumbnailWidth?: number;
}

/**
 * Where attachment bytes live. Callers pass a canonical key
 * `tenantId/yyyy/mm/<attachmentId>.<ext>`; `put` returns the key to store on the
 * Attachment row (a provider may use its own format, e.g. `cloudinary:image:<public_id>`).
 */
export interface StorageProvider {
  readonly name: string;
  /** Stores the bytes and returns the storage key to persist. */
  put(key: string, buffer: Buffer, mime: string): Promise<string>;
  /** Short-lived URL a client can GET without other credentials. */
  getSignedUrl(key: string, ttlSec: number, options?: SignedUrlOptions): Promise<{ url: string; expiresAt: Date }>;
  delete(key: string): Promise<void>;
  /** Streams bytes through this API (local provider only). */
  open(key: string): Promise<{ stream: Readable; size: number }>;
}

const KEY_PATTERN = /^([0-9a-f-]{36})\/(\d{4})\/(\d{2})\/([0-9a-f-]{36})\.([a-z0-9]{1,5})$/;

/** Splits a storage key into tenant and attachment id. Throws for anything unexpected. */
export function parseStorageKey(key: string): { tenantId: string; attachmentId: string } {
  const match = KEY_PATTERN.exec(key);
  if (!match) throw new Error(`Invalid storage key: ${key}`);
  return { tenantId: match[1]!, attachmentId: match[4]! };
}

/** HMAC over attachment id + tenant + expiry. The pepper never leaves the server. */
export function fileSignature(attachmentId: string, tenantId: string, exp: number): string {
  return createHmac('sha256', env.JWT_REFRESH_PEPPER).update(`attachment:${attachmentId}:${tenantId}:${exp}`).digest('base64url');
}

export function verifyFileSignature(attachmentId: string, tenantId: string, exp: number, sig: string): boolean {
  const expected = Buffer.from(fileSignature(attachmentId, tenantId, exp));
  const given = Buffer.from(sig);
  return expected.length === given.length && timingSafeEqual(expected, given);
}

/**
 * Stores files on the local disk under STORAGE_DIR. Signed URLs point back at this API:
 * /api/v1/attachments/:id/file?tid=&exp=&sig=
 */
export class LocalStorageProvider implements StorageProvider {
  readonly name = 'local';
  private readonly root: string;

  constructor(root: string) {
    this.root = resolve(root);
  }

  private pathFor(key: string): string {
    parseStorageKey(key); // rejects traversal and anything not generated by us
    const full = resolve(this.root, key);
    if (!full.startsWith(this.root + sep)) throw new Error('Storage path escapes the root');
    return full;
  }

  async put(key: string, buffer: Buffer): Promise<string> {
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, buffer, { flag: 'wx' });
    return key;
  }

  async getSignedUrl(key: string, ttlSec: number): Promise<{ url: string; expiresAt: Date }> {
    const { tenantId, attachmentId } = parseStorageKey(key);
    const exp = Math.floor(Date.now() / 1000) + ttlSec;
    const query = new URLSearchParams({ tid: tenantId, exp: String(exp), sig: fileSignature(attachmentId, tenantId, exp) });
    return { url: `${apiPublicUrl}/api/v1/attachments/${attachmentId}/file?${query}`, expiresAt: new Date(exp * 1000) };
  }

  async delete(key: string): Promise<void> {
    await rm(this.pathFor(key), { force: true });
  }

  async open(key: string): Promise<{ stream: Readable; size: number }> {
    const path = this.pathFor(key);
    const info = await stat(path);
    return { stream: createReadStream(path), size: info.size };
  }
}

let local: LocalStorageProvider | undefined;
let cloudinary: StorageProvider | undefined;
let override: StorageProvider | undefined;

function localProvider(): LocalStorageProvider {
  return (local ??= new LocalStorageProvider(env.STORAGE_DIR));
}

function cloudinaryProvider(): StorageProvider {
  if (override) return override;
  if (!cloudinary) {
    cloudinary = new CloudinaryStorageProvider({
      cloudName: env.CLOUDINARY_CLOUD_NAME!,
      apiKey: env.CLOUDINARY_API_KEY!,
      apiSecret: env.CLOUDINARY_API_SECRET!,
      authTokenKey: env.CLOUDINARY_AUTH_TOKEN_KEY,
    });
  }
  return cloudinary;
}

/** Provider for NEW uploads (STORAGE_PROVIDER). */
export function storage(): StorageProvider {
  if (override) return override;
  return env.STORAGE_PROVIDER === 'cloudinary' ? cloudinaryProvider() : localProvider();
}

/**
 * Provider that holds an EXISTING key. Keys say where they live, so switching
 * STORAGE_PROVIDER keeps older files readable.
 */
export function storageForKey(key: string): StorageProvider {
  return isCloudinaryKey(key) ? cloudinaryProvider() : localProvider();
}

/** Tests only: route uploads (and cloudinary keys) to a given provider; undefined resets. */
export function useStorageProviderForTests(provider: StorageProvider | undefined): void {
  override = provider;
}
