import { Router } from 'express';
import swaggerUi from 'swagger-ui-express';
import { registerAttachmentsDocs } from '../../modules/attachments/attachments.docs.js';
import { registerAuthDocs } from '../../modules/auth/auth.docs.js';
import { registerCompanyDocs } from '../../modules/company/company.docs.js';
import { registerHealthDocs } from '../../modules/health/health.routes.js';
import { registerTeamDocs } from '../../modules/team/team.docs.js';
import { buildOpenApiDocument } from './registry.js';
import { swaggerCss, swaggerFavicon } from './theme.js';

let document: ReturnType<typeof buildOpenApiDocument> | undefined;

/** Registers every module's docs once and builds the OpenAPI document. */
export function openApiDocument() {
  if (!document) {
    registerHealthDocs();
    registerAuthDocs();
    registerCompanyDocs();
    registerTeamDocs();
    registerAttachmentsDocs();
    document = buildOpenApiDocument();
  }
  return document;
}

/** Swagger UI at /api/docs and the raw spec at /api/docs.json. */
export function docsRouter(): Router {
  const router = Router();
  const spec = openApiDocument();
  router.get('/docs.json', (_req, res) => {
    res.json(spec);
  });
  const html = swaggerUi
    .generateHTML(spec, {
      customSiteTitle: 'Construction Platform API',
      customCss: swaggerCss,
      customfavIcon: swaggerFavicon,
      swaggerOptions: {
        persistAuthorization: true, // keep the pasted Bearer token across reloads
        withCredentials: true, // send the httpOnly auth cookies on "Try it out"
        tryItOutEnabled: true,
        displayRequestDuration: true,
        docExpansion: 'list',
        defaultModelsExpandDepth: 0,
        defaultModelExpandDepth: 3,
        filter: true,
        deepLinking: true, // /api/docs/#/Auth/post_api_v1_auth_login opens that endpoint
        syntaxHighlight: { activated: true, theme: 'idea' },
      },
    })
    // swagger-ui-express ships no viewport tag, so phones would render a shrunken desktop page.
    .replace('<meta charset="UTF-8">', '<meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">');

  router.get('/docs', (req, res) => {
    // Assets are referenced relatively (./swagger-ui.css), so the page must live at /docs/.
    if (!req.originalUrl.split('?')[0]!.endsWith('/')) return res.redirect(301, `${req.baseUrl}/docs/`);
    res.type('html').send(html);
  });
  // Static assets + swagger-ui-init.js (generated by generateHTML above).
  router.use('/docs', swaggerUi.serve);
  return router;
}
